server:
  port: 4000
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test
    username: root
    password: 123456
  http:
    encoding:
      enabled: true
      charset: UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

rsa:
  key:
    pubKeyFile: D:\\auth_key\\id_key_rsa.pub
    priKeyFile: D:\\auth_key\\id_key_rsa